import { ProjectCard } from "@/interface/projectCard"
import { User, RoleName, FreelancerProfile } from "@/interface/user"
import { Job } from "@/interface/job"

export const MOCK_PROJECT_CARDS: ProjectCard[] = [
  {
    id: "pc-001",
    title: "Aether Data Platform v2.0",
    subtitle: "Enterprise Web Platform",
    coverImageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    categoryId: "web-dev",
    freelanceId: "u1",
    publishedAt: "2026-09-18T09:00:00Z",
    likeCount: 428,
    viewCount: 12400,
  },
  {
    id: "pc-002",
    title: "Nexus Pay — Wealth & Transfers",
    subtitle: "iOS & Android App",
    coverImageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
    categoryId: "mobile-dev",
    freelanceId: "u2",
    publishedAt: "2026-09-17T14:30:00Z",
    likeCount: 812,
    viewCount: 28100,
  },
  {
    id: "pc-003",
    title: "Kroma Creative Studio Identity",
    subtitle: "Brand Architecture",
    coverImageUrl: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=800&auto=format&fit=crop&q=80",
    categoryId: "branding",
    freelanceId: "u3",
    publishedAt: "2026-09-16T11:15:00Z",
    likeCount: 540,
    viewCount: 15300,
  },
  {
    id: "pc-004",
    title: "Cloud Infrastructure Migration",
    subtitle: "DevOps & IT Consulting",
    coverImageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
    categoryId: "it-software",
    freelanceId: "u4",
    publishedAt: "2026-09-15T08:45:00Z",
    likeCount: 1200,
    viewCount: 34700,
  },
  {
    id: "pc-005",
    title: "Bauhaus Redux Editorial System",
    subtitle: "Print & Poster Design",
    coverImageUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80",
    categoryId: "graphic-design",
    freelanceId: "u5",
    publishedAt: "2026-09-14T16:20:00Z",
    likeCount: 389,
    viewCount: 9800,
  },
  {
    id: "pc-006",
    title: "Maison Vesper Fragrances",
    subtitle: "Shopify & Headless Commerce",
    coverImageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80",
    categoryId: "web-dev",
    freelanceId: "u6",
    publishedAt: "2026-09-13T10:05:00Z",
    likeCount: 714,
    viewCount: 22600,
  },
  {
    id: "pc-007",
    title: "Synapse Studio — Node AI",
    subtitle: "Complex App UX",
    coverImageUrl: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80",
    categoryId: "uiux",
    freelanceId: "u7",
    publishedAt: "2026-09-12T13:40:00Z",
    likeCount: 960,
    viewCount: 31000,
  },
  {
    id: "pc-008",
    title: "Q3 Growth Campaign Report",
    subtitle: "Digital Marketing & Analytics",
    coverImageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    categoryId: "digital-marketing",
    freelanceId: "u8",
    publishedAt: "2026-09-11T07:50:00Z",
    likeCount: 1500,
    viewCount: 41200,
  },
  {
    id: "pc-009",
    title: "Wanderlust Travel App Redesign",
    subtitle: "Mobile UX Case Study",
    coverImageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80",
    categoryId: "uiux",
    freelanceId: "u9",
    publishedAt: "2026-09-10T12:10:00Z",
    likeCount: 623,
    viewCount: 18900,
  },
  {
    id: "pc-010",
    title: "Verdant Botanicals Brand Launch",
    subtitle: "Product Copy & Content",
    coverImageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    categoryId: "writing",
    freelanceId: "u10",
    publishedAt: "2026-09-09T15:25:00Z",
    likeCount: 275,
    viewCount: 7600,
  },
]

export const MOCK_USERS: User[] = [
  {
    userId: "u1",
    name: "Alex Vance",
    username: "alexvance",
    role: RoleName.FREELANCER,
    email: "alex.vance@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-01-15T08:30:00Z",
    updatedAt: "2026-09-18T10:00:00Z",
    lastLoginAt: "2026-09-19T09:15:00Z",
  },
  {
    userId: "u2",
    name: "Sarah Chen",
    username: "sarahchen",
    role: RoleName.FREELANCER,
    email: "sarah.chen@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-02-10T11:20:00Z",
    updatedAt: "2026-09-17T15:00:00Z",
    lastLoginAt: "2026-09-19T11:45:00Z",
  },
  {
    userId: "u3",
    name: "Marcus Aurelius",
    username: "marcus_design",
    role: RoleName.FREELANCER,
    email: "marcus.a@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-03-01T09:10:00Z",
    updatedAt: "2026-09-16T12:00:00Z",
    lastLoginAt: "2026-09-18T16:30:00Z",
  },
  {
    userId: "u4",
    name: "David Kim",
    username: "davidkim_cloud",
    role: RoleName.FREELANCER,
    email: "david.kim@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-01-20T14:40:00Z",
    updatedAt: "2026-09-15T09:00:00Z",
    lastLoginAt: "2026-09-19T08:00:00Z",
  },
  {
    userId: "u5",
    name: "Elena Rostova",
    username: "elena_arts",
    role: RoleName.FREELANCER,
    email: "elena.rostova@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-04-12T16:15:00Z",
    updatedAt: "2026-09-14T17:00:00Z",
    lastLoginAt: "2026-09-17T20:10:00Z",
  },
  {
    userId: "u6",
    name: "Liam O'Connor",
    username: "liam_dev",
    role: RoleName.FREELANCER,
    email: "liam.oconnor@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-02-28T10:05:00Z",
    updatedAt: "2026-09-13T11:00:00Z",
    lastLoginAt: "2026-09-19T10:20:00Z",
  },
  {
    userId: "u7",
    name: "Maya Patel",
    username: "mayapatel_ui",
    role: RoleName.FREELANCER,
    email: "maya.patel@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-03-18T13:25:00Z",
    updatedAt: "2026-09-12T14:00:00Z",
    lastLoginAt: "2026-09-19T12:00:00Z",
  },
  {
    userId: "u8",
    name: "Carlos Mendez",
    username: "carlos_growth",
    role: RoleName.FREELANCER,
    email: "carlos.mendez@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    status: "PENDING_VERIFICATION",
    createdAt: "2026-05-05T08:00:00Z",
    updatedAt: "2026-09-11T08:00:00Z",
    lastLoginAt: "2026-09-15T14:30:00Z",
  },
  {
    userId: "u9",
    name: "Sophia Nguyen",
    username: "sophianguyen",
    role: RoleName.CLIENT,
    email: "sophia.nguyen@example.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2026-01-10T07:45:00Z",
    updatedAt: "2026-09-10T12:30:00Z",
    lastLoginAt: "2026-09-18T18:00:00Z",
  },
  {
    userId: "u10",
    name: "Oliver Wright",
    username: "oliverwright",
    role: RoleName.ADMIN,
    email: "admin.oliver@eykorban.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    status: "ACTIVE",
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2026-09-09T15:30:00Z",
    lastLoginAt: "2026-09-19T13:00:00Z",
  },
]

export const CURRENT_USER_ID = "u1"

export const MOCK_FREELANCER_PROFILES: FreelancerProfile[] = [
  {
    userId: "u1",
    username: "alexvance",
    tagline: "Full-stack engineer for data-heavy web platforms",
    bio: "I design and build web platforms that turn messy data into clear dashboards. Eight years shipping React and Node products for analytics and enterprise teams, from first prototype to production scale.",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Data Viz"],
    hourlyRate: 85,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: {
      website: "https://alexvance.dev",
      github: "https://github.com/alexvance",
    },
  },
  {
    userId: "u2",
    username: "sarahchen",
    tagline: "Mobile designer and developer for fintech",
    bio: "I make money apps people actually trust. I work across product design and native development, so the handoff between Figma and Swift or Kotlin never gets lost.",
    skills: ["Swift", "Kotlin", "React Native", "Fintech UX"],
    hourlyRate: 95,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { linkedin: "https://linkedin.com/in/sarahchen" },
  },
  {
    userId: "u3",
    username: "marcus_design",
    tagline: "Brand identity designer for creative studios",
    bio: "Identity systems with a point of view. I help studios and agencies find a visual voice, then document it so the whole team can use it.",
    skills: ["Branding", "Logo Design", "Typography", "Art Direction"],
    hourlyRate: 70,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { website: "https://marcus.design" },
  },
  {
    userId: "u4",
    username: "davidkim_cloud",
    tagline: "Cloud architect moving teams to AWS and GCP",
    bio: "I plan and run cloud migrations with zero-downtime cutovers, then leave teams with infrastructure as code they can own.",
    skills: ["AWS", "Terraform", "Kubernetes", "DevOps"],
    hourlyRate: 110,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { linkedin: "https://linkedin.com/in/davidkim" },
  },
  {
    userId: "u5",
    username: "elena_arts",
    tagline: "Editorial designer with a Bauhaus streak",
    bio: "Grids, bold type and primary colours. I design magazines, reports and editorial systems for print and screen.",
    skills: ["Editorial Design", "Layout", "Print", "Illustration"],
    hourlyRate: 65,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { website: "https://elenarostova.art" },
  },
  {
    userId: "u6",
    username: "liam_dev",
    tagline: "Creative developer for luxury e-commerce",
    bio: "I build storefronts that feel like the brand: smooth motion, fast pages and checkout flows that convert.",
    skills: ["Shopify", "Next.js", "GSAP", "Three.js"],
    hourlyRate: 80,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { github: "https://github.com/liamdev" },
  },
  {
    userId: "u7",
    username: "mayapatel_ui",
    tagline: "UI/UX designer for AI and developer tools",
    bio: "I simplify complex tools. Most of my work is design systems and interaction design for AI products and developer platforms.",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    hourlyRate: 90,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { website: "https://mayapatel.design" },
  },
  {
    userId: "u8",
    username: "carlos_growth",
    tagline: "Growth marketer turning data into campaigns",
    bio: "Campaign strategy backed by numbers. I run SEO, paid acquisition and reporting for early-stage brands.",
    skills: ["SEO", "Paid Ads", "Analytics", "Copywriting"],
    hourlyRate: 60,
    currency: "USD",
    publicProfileEnabled: true,
    socialLinks: { linkedin: "https://linkedin.com/in/carlosmendez" },
  },
]

export const MOCK_JOBS: Job[] = [
  {
    id: "job-001",
    clientId: "u9",
    title: "Landing page for a fintech savings app",
    description:
      "We are launching a round-up savings app and need a high-converting landing page with a clear signup flow. Design and build in React; copy is ready.",
    categoryId: "web-dev",
    industryId: "fintech",
    status: "open",
    publishedAt: "2026-09-19T08:00:00Z",
  },
  {
    id: "job-002",
    clientId: "u9",
    title: "Brand identity for an organic skincare line",
    description:
      "New skincare brand looking for a full identity: logo, colour palette, typography and packaging direction for five products. Earthy, calm and premium.",
    categoryId: "branding",
    industryId: "ecommerce",
    status: "open",
    publishedAt: "2026-09-18T13:30:00Z",
  },
  {
    id: "job-003",
    clientId: "u9",
    title: "iOS app redesign for a telehealth startup",
    description:
      "Our booking and video-visit flows are dated and confusing for older patients. We need a redesign focused on accessibility, then help implementing it in SwiftUI.",
    categoryId: "mobile-dev",
    industryId: "healthcare",
    status: "open",
    publishedAt: "2026-09-17T10:15:00Z",
  },
  {
    id: "job-004",
    clientId: "u9",
    title: "Attendance dashboard for a school network",
    description:
      "Build a dashboard that shows attendance trends across twelve schools, with filters by grade and term. Data comes from a CSV export updated weekly.",
    categoryId: "data-analytics",
    industryId: "education",
    status: "open",
    publishedAt: "2026-09-16T09:00:00Z",
  },
  {
    id: "job-005",
    clientId: "u9",
    title: "Explainer video for a property listing platform",
    description:
      "A 60-second animated explainer showing how buyers find and book viewings on our platform. Script is drafted; we need storyboard, animation and voice-over.",
    categoryId: "video-animation",
    industryId: "real-estate",
    status: "open",
    publishedAt: "2026-09-15T16:45:00Z",
  },
  {
    id: "job-006",
    clientId: "u9",
    title: "Design system audit for a SaaS product",
    description:
      "Our Figma library has drifted from the code. Audit components, document the gaps and propose a cleaned-up set of tokens and core components.",
    categoryId: "uiux",
    industryId: "tech",
    status: "open",
    publishedAt: "2026-09-14T11:20:00Z",
  },
  {
    id: "job-007",
    clientId: "u9",
    title: "SEO content plan for an online bookstore",
    description:
      "Plan and write twelve long-form articles around reading lists and gift guides, with keyword research and internal linking recommendations.",
    categoryId: "writing",
    industryId: "ecommerce",
    status: "open",
    publishedAt: "2026-09-12T07:30:00Z",
  },
  {
    id: "job-008",
    clientId: "u9",
    title: "Podcast cover art and social templates",
    description:
      "Cover art for a weekly film podcast plus editable templates for episode announcements on Instagram and YouTube.",
    categoryId: "graphic-design",
    industryId: "entertainment",
    status: "closed",
    publishedAt: "2026-09-10T15:00:00Z",
  },
]
