import { ProjectCard } from "@/interface/projectCard";

export const MOCK_PROJECT_CARDS: ProjectCard[] = [
  {
    id: "pc-001",
    title: "Aether Data Platform v2.0",
    subtitle: "Enterprise Web Platform",
    coverImageUrl: "https://picsum.photos/seed/aether-platform/640/480",
    categoryId: "web-dev",
    freelanceId: "u1",
    publishedAt: "2026-09-18T09:00:00Z",
    likeCount: 428,
    viewCount: 12400,
  },
  {
    id: "pc-002",
    title: "Nexus Pay — Wealth & Transfers",
    subtitle: "iOS & Android App",
    coverImageUrl: "https://picsum.photos/seed/nexus-pay/640/480",
    categoryId: "mobile-dev",
    freelanceId: "u2",
    publishedAt: "2026-09-17T14:30:00Z",
    likeCount: 812,
    viewCount: 28100,
  },
  {
    id: "pc-003",
    title: "Kroma Creative Studio Identity",
    subtitle: "Brand Architecture",
    coverImageUrl: "https://picsum.photos/seed/kroma-brand/640/480",
    categoryId: "branding",
    freelanceId: "u3",
    publishedAt: "2026-09-16T11:15:00Z",
    likeCount: 540,
    viewCount: 15300,
  },
  {
    id: "pc-004",
    title: "Cloud Infrastructure Migration",
    subtitle: "DevOps & IT Consulting",
    coverImageUrl: "https://picsum.photos/seed/cloud-migration/640/480",
    categoryId: "it-software",
    freelanceId: "u4",
    publishedAt: "2026-09-15T08:45:00Z",
    likeCount: 1200,
    viewCount: 34700,
  },
  {
    id: "pc-005",
    title: "Bauhaus Redux Editorial System",
    subtitle: "Print & Poster Design",
    coverImageUrl: "https://picsum.photos/seed/bauhaus-redux/640/480",
    categoryId: "graphic-design",
    freelanceId: "u5",
    publishedAt: "2026-09-14T16:20:00Z",
    likeCount: 389,
    viewCount: 9800,
  },
  {
    id: "pc-006",
    title: "Maison Vesper Fragrances",
    subtitle: "Shopify & Headless Commerce",
    coverImageUrl: "https://picsum.photos/seed/maison-vesper/640/480",
    categoryId: "web-dev",
    freelanceId: "u6",
    publishedAt: "2026-09-13T10:05:00Z",
    likeCount: 714,
    viewCount: 22600,
  },
  {
    id: "pc-007",
    title: "Synapse Studio — Node AI",
    subtitle: "Complex App UX",
    coverImageUrl: "https://picsum.photos/seed/synapse-studio/640/480",
    categoryId: "uiux",
    freelanceId: "u7",
    publishedAt: "2026-09-12T13:40:00Z",
    likeCount: 960,
    viewCount: 31000,
  },
  {
    id: "pc-008",
    title: "Q3 Growth Campaign Report",
    subtitle: "Digital Marketing & Analytics",
    coverImageUrl: "https://picsum.photos/seed/growth-campaign/640/480",
    categoryId: "digital-marketing",
    freelanceId: "u8",
    publishedAt: "2026-09-11T07:50:00Z",
    likeCount: 1500,
    viewCount: 41200,
  },
  {
    id: "pc-009",
    title: "Wanderlust Travel App Redesign",
    subtitle: "Mobile UX Case Study",
    coverImageUrl: "https://picsum.photos/seed/wanderlust-app/640/480",
    categoryId: "uiux",
    freelanceId: "u9",
    publishedAt: "2026-09-10T12:10:00Z",
    likeCount: 623,
    viewCount: 18900,
  },
  {
    id: "pc-010",
    title: "Verdant Botanicals Brand Launch",
    subtitle: "Product Copy & Content",
    coverImageUrl: "https://picsum.photos/seed/verdant-botanicals/640/480",
    categoryId: "writing",
    freelanceId: "u10",
    publishedAt: "2026-09-09T15:25:00Z",
    likeCount: 275,
    viewCount: 7600,
  },
];

